_target_: pi3.models.pi3x.Pi3X
ckpt: ${oc.env:PI3X_CKPT,null}
use_multimodal: true
encoder_pretrained: ${oc.env:PI3X_ENCODER_PRETRAINED,true}
hamer_config_file: ${oc.env:HAMER_CONFIG_FILE,configs/hamer/model_config.yaml}
hamer_cache_dir: ${oc.env:HAMER_CACHE_DIR,data/model/hamer/_DATA}
hand_mano_layer: null
ho_lora_cfg:
  rank: 4
  alpha: 8
  targets: ["cross_attn"]
